Avoid adding duplicate inline CSS
orlov-vo/parcel-transformer-svelte pull request #9
Opened 2020-09-19 23:08 UTC by canadaduane

Fixes #8

2020-09-20 04:15 UTC, canadaduane commented on index.js
> +    const options = Object.assign({ css: false }, options.compiler);
This causes an error--`options` is shadowing the `options` argument. Need to fix.

2020-09-20 04:19 UTC, canadaduane commented on index.js
> +    const options = Object.assign({ css: false }, options.compiler);
I'm also not sure why the compiler options in `getConfig` are not being picked up here, since css is set to `false` there also. Hmm.

2020-09-23 20:35 UTC, orlov-vo requested changes

2020-09-23 20:35 UTC, orlov-vo commented on index.js
> +const path = require("path");
please remove codestyle changes from your PR

2020-09-23 21:09 UTC, closed without merging

2020-09-23 22:14 UTC, canadaduane commented on index.js
> +const { exit } = require("process");
This can be removed. I was using process.exit to debug under certain conditions where logging output was not being shown.